### ISSUE TITLE
Automate build on DockerHub

### ISSUE THREAD

**Issue by a-magdy** [rwynn/monstache-builder#1]
Hi @rwynn,

Thanks for creating the repo 🎉 

Could you please create an automated build for this repo on the tag `v1.0.0` => `rwynn/monstache-builder:1.0.0`

**Comment by rwynn** [comment]
Automated build is setup now for `monstache-builder` and a version `1.0.0` is tagged to the first build. Thanks.

**Comment by rwynn** [comment]
I also created automated builds for the `monstache` repo.  The tags will be `latest` for master branch and `rel3` for rel3 branch.  https://hub.docker.com/r/rwynn/monstache-builds/

**Comment by a-magdy** [comment]
That is great, thanks :) , but now monstache tool is named: `rwynn/monstache-builds:lastest` & `rwynn/monstache-builds:rel3` and not `rwynn/monstache:latest&rel3`

**Comment by rwynn** [comment]
I couldn’t figure out how to convert an existing docker repo to an automated build one. It kept saying the name was already taken.

**Comment by a-magdy** [comment]
Hmm, maybe we can contact DockerHub support, or go for the worse solution, which is removing it and creating it with an automated build, then push old images again

**Comment by a-magdy** [comment]
One way would be to download all existing images locally, and push them again once the new automated one is created, I could right a script to pull and push these images, it'll be just a matter of download and upload time

**Comment by a-magdy** [comment]
We could use this script to download all existing tags locally, download them, and upload them with the same name at a later point in time (or even push all images to a different repo on DockerHub

```bash
TAGS_FILE_NAME=${TAGS_FILE_NAME:-monstache-tags.txt}
SOURCE_REPO_NAME=rwynn/monstache
TARGET_REPO_NAME=rwynn/monstache-builds

# # Step 1: Save all current tags to a file (if it doesn't already exist)
if [ ! -f "$TAGS_FILE_NAME" ] ; then
  (wget -q https://registry.hub.docker.com/v1/repositories/rwynn/monstache/tags -O -  | sed -e 's/[][]//g' -e 's/"//g' -e 's/ //g' | tr '}' '\n'  | awk -F: '{print $3}') > "$TAGS_FILE_NAME"
fi

# Step 2: Download all images
if [ -f "$TAGS_FILE_NAME" ] ; then
  while read -r line
  do
      echo ${line}
      docker pull "$SOURCE_REPO_NAME:$line"
  done < ${TAGS_FILE_NAME}
fi

# Step 3: Upload all images (at a later point in time)
if [ -f "$TAGS_FILE_NAME" ] ; then
  while read -r line
  do
      echo ${line}

      # docker push "$SOURCE_REPO_NAME:$line"

      docker tag "$SOURCE_REPO_NAME:$line" "$TARGET_REPO_NAME:$line"
      docker push "$TARGET_REPO_NAME:$line"
  done < ${TAGS_FILE_NAME}
fi
```

**Comment by a-magdy** [comment]
If you give me access to the `rwynn/monstache-builds` repo, I could copy all images to this repo as a backup, then we could remove the original `rwynn/monstache`, create an automated build, and upload all images to it again using the same script, what do you think?

**Comment by rwynn** [comment]
Actually, I think I figured out how to do it.  Needed to switch from `hub.docker.com` over to `cloud.docker.com` which does have the ability to add an automated build after the fact.

https://github.com/docker/hub-feedback/issues/794

**Comment by rwynn** [comment]
The builds are done now, so all should be good with automated `rwynn/monstache:latest` and `rwynn/monstache:rel3`.

**Comment by a-magdy** [comment]
Cool, but when I opened cloud.docker.com it had a warming that it will be discontinued on 21 May, will this affect the automated builds later?

**Comment by rwynn** [comment]
I think it’s OK for now.   See -what stays-...

https://docs.docker.com/docker-cloud/migration/

**Comment by a-magdy** [comment]
Ah, this is great :) 

Well in this case I think this issue can be closed :)

Thanks for your work as always, I'll create others for the next steps and CI
